language: python
cache: 
  - pip
python:
  - "3.6"

before_script:
  - pip install -r requirements.txt
script:
  - echo "Building and Testing"
  - sleep 10
after_script:
  - curl -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d "text=Frontend Deployed https://morejust.github.io/russianhackteam"